// This file is generated by scripts/generate-preload-types.mjs.
// Do not edit directly. Update src/preload/api.ts, then run npm run preload:types.

import type {
  DroppedSettingsEntry as PreloadDroppedSettingsEntry,
  DroppedSettingsRecordField as PreloadDroppedSettingsRecordField,
  ElectronAPI,
  MigrationFlags as PreloadMigrationFlags,
  SaveSettingsResult as PreloadSaveSettingsResult,
  Settings as PreloadSettings,
  StoreConfigChangePayload as PreloadStoreConfigChangePayload,
  StoreConfigChangeReason as PreloadStoreConfigChangeReason,
  WritableSettings as PreloadWritableSettings
} from './api'

export {}

declare global {
  type Settings = PreloadSettings

  type WritableSettings = PreloadWritableSettings

  type MigrationFlags = PreloadMigrationFlags

  type StoreConfigChangeReason = PreloadStoreConfigChangeReason

  type StoreConfigChangePayload = PreloadStoreConfigChangePayload

  type DroppedSettingsRecordField = PreloadDroppedSettingsRecordField

  type DroppedSettingsEntry = PreloadDroppedSettingsEntry

  type SaveSettingsResult = PreloadSaveSettingsResult

  interface Window {
    electronAPI: ElectronAPI
  }
}
