export { killLaunchedApps, killProfileApps } from './processes/kill'
export { getRunningApps } from './processes/running'
export { launchProfileApps, isRunningExePath } from './processes/spawn'
export { readRunningProcessNames } from './processes/tasklist'
export type { KillResult, LaunchResult } from './processes/types'
